# The official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Specify your arguments
CMD ["python3", "-u", "./unicast_master.py"]

