# The official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Set your script as the entrypoint
ENTRYPOINT [ "python3",  "unicast_node.py"]
