# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Run the script when the container launches
# Note: The CMD will be overridden if specified in the docker run command
CMD ["python3", "-u", "./multicast_master.py"]

