# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Set your script as the entrypoint
ENTRYPOINT ["python3", "multicast_node.py"]

# Specify default arguments
CMD ["1", "Message from node 1"]